### ISSUE TITLE
Liquidate & Profit distribution

### ISSUE THREAD

**Issue by wd30130** [Magport/Magnet#15]
We should build module to realize automatic system income and expenses (Gas income, Coretime purchase expense compensation and incentives, etc.) liquidation and automatic profit distribution.

**Comment by Acaishiba** [comment]
We need an interface that can provide detailed information for each coretime receipt
For example: [`Coretime_Detail`, `Coretime_Buyer`, `Coretime_Cost`]

Regarding the profit calculation mechanism, There are some parameter definitions:
Every `Era`, Calculate the `Total_income` of the Magnet:
**`Total_Income`** = Gas_block1+Gas_block2+...+Gas_blockN

Every `Era`, Calculate the `Total_cost` of the `Coretime`
**`Total_Cost`**=Coretime_Cost1+Coretime_Cost2+...+CoretimeCostN

Every `Era`, Calculate the `Total_Profit` of the `Era`
**`Total_Profit`** = `Total_income` - `Total_Cost`

Handle Profit
If `Total_Profit` > 0, Allocate Profit
**`Profit_Allocate`**(`System_Reserve`, `Relaychain_Treasury,` `Operation_Reserve`, `Collator_Profit`, `Total_Profit`)
Regarding `Collator_Profit`, Allocate profit to collators based on the `Coretime_Cost`, `Collator_Profit` and `Total_Cost`

If `Total_Profit` <=0, Deduct from System_Reserve
**`Reserve_Deduct`**(`System_Reserve`, `Total_Profit`)

Return `Coretime_Cost `to corresponding `Coretime_Buyer`
**`Return_Cost`**(`Coretime_Buyer`, `Coretime_Cost`)

**Comment by Acaishiba** [comment]
@toints
