### ISSUE TITLE
Use XCM failed on branch polkadot-v1.7

### ISSUE THREAD

**Issue by zachary0809** [Magport/Magnet#62]
When using XCM's function reserveTransferAsset between Polkadot-v1.7 Magnet and Polkadot-SDK-v1.7.0, it's okay for the relay chain to send to the parachain, but it fails when the parachain tries to send back to the relay chain. The error is messagesQueue.ProcessingFailed,errCode is Corrupt.

**Comment by wd30130** [comment]
Closed by #66
