### ISSUE TITLE
Gas cost is only calculated in ondemand mode

### ISSUE THREAD

**Issue by sulijia** [Magport/Magnet#68]
Gas cost should not be calculated in parachain mode and parathread bulk mode.

Therefore, the gas_cost function should return a Result type. 
When it is Err, it represents an error returned in ondemand mode. 
When it is OK (None), it represents other modes, and gas cost should not be calculated. 
When it is OK (Some), it represents ondemand mode, and gas cost needs to be calculated.

**Comment by wd30130** [comment]
closed by pr#69
